### ISSUE TITLE
Improve ResolveInfo to check for fields in query

### ISSUE THREAD

**Issue by beberlei** [youshido-php/GraphQL#169]
Currently there is no easy way (boolean) to check if a field was selected in a query. Fetching of a field in an object could be computationally expensive, so i would like to check if the user wants this field before returning it from resolve:

```php
public function resolve($value, array $args, ResolveInfo $info)
{
    $data = ['id'  => 1];
    if ($info->hasField('expensiveThing')) {
        $data['expensive'] = "xyz";
    }
    return $data;
}
```

For this, `ResolveInfo#fieldASTList should not be a list, but instead indexed by field name, so that we can introduce:

```php
class ResolveInfo
{
    public function hasField($name)
    {
          return isset($this->fieldASTList[$name];
    }
}
```

Now I have to loop over `getFieldASTList()` and check name manually in each element, it is a bit complicated to use.

**Comment by fritz-gerneth** [comment]
May I suggest an alternative to your problem: instead of having the parent to check for a child field to be present I think the correct way is to actually have a separate resolve function for the `expensiveThing` field. This keeps both parent and child fields isolated from each other and re-usable.

The key for this to work is the `$value` argument of the resolve function - it's the parent's value (remember, GraphQL queries are resolved top-to-bottom). 

Some (untested) example how this would look like:
```
$processor = new Processor(new Schema([
    'query' => new ObjectType([
        'name'   => 'RootQueryType',
        'fields' => [
            'latestPost' => [
                'type'    => new ObjectType([
                    'name'    => 'Post',
                    'fields'  => [
                        'id'   => new IdType(),  
                        'expensiveThing' => new ObjectType([
				  'resolve' => function ($value, $args, $info) {
					// $value is now ['id'  => 1]
					return getExpensiveThing($value['id']);
				},
			]),
                    ],
                ]),
                'resolve' => function () {        
                    return ['id'  => 1];
                }
            ]
        ]
    ])
]));
```

**Comment by beberlei** [comment]
@fritz-gerneth that is a good help. What if in the top level resolve for latestPost I have already fetched a database object `$post` that i want to pass on to child resolve functions, is that possible somehow?

**Comment by fritz-gerneth** [comment]
This really depends on your implementation - if you do return `$post` in your parent's resolve function it will get passed in as `$value` in the child. If not, you might need to use some out-of-band intermediate storage (e.g. doctrine orm would handle this for you).

**Comment by ChristianVermeulen** [comment]
I created a simple static method helper class for this in the time being, if that helps anyone. Please not I only needed to find Query fields, so you might want to adapt to support others as well.

```php
<?php

namespace Your\App;

use Youshido\GraphQL\Parser\Ast\Query;

class IsQueryPresent
{
    /**
     * @param string $query
     * @param array  $fieldASTList
     * @return bool
     */
    public static function forFieldASTList(string $query, array $fieldASTList): bool
    {
        foreach ($fieldASTList as $field) {
            if (!$field instanceof Query) {
                continue;
            }

            if($field->getName() === $query) {
                return true;
            }
        }

        return false;
    }
}
```

**Comment by Jalle19** [comment]
I've contemplated this issue myself when I've stumbled upon similar performance issues, and like @fritz-gerneth said the go-to solution has been to re-think the solution and introduce a separate resolver for expensive fields instead.

I think most of this are implementation details and no proper solution really belongs in the library, at least in the current state. Closing this.
