### ISSUE TITLE
[introspection] types only implementing an interface aren’t loaded by the schema

### ISSUE THREAD

**Issue by mathroc** [youshido-php/GraphQL#193]
I have a types that implements an interface, but they’re not used anywhere else. Making query against them `... on SomeType { field1, field2}` works but in graphiql they’re not shown when browsing the doc in the `implémentations` section of the interface

to work around this I have to register them on the schema manually with `$this->getTypesList()->addTypes([…]);`

maybe an optional `getImplementations()` could be added to `AbstractInterfaceType` to take care of this ?

**Comment by skyzyx** [comment]
Do you have a PR that addresses this?

**Comment by Jalle19** [comment]
Not sure if I actually fixed this issue or not. We've resorted to the same workaround in one of our projects, I have to test there if the thing is actually fixed or not.
