### ISSUE TITLE
impossible to set null as defaultValue

### ISSUE THREAD

**Issue by revlis7** [youshido-php/GraphQL#194]
https://github.com/Youshido/GraphQL/blob/875ce0c911dec6297b2239195926c70de5700157/src/Execution/Processor.php#L583

Is there a way to set a null value as a default value? Or I have to set a null value explicitly in the request?

```php
public function build(FieldConfig $config)
{
    $config->addArguments([
        'age' => [
            'type' => new IntType,
            'defaultValue' => 24, // this is fine
            // 'defaultValue' => null, // null value is not supported?
        ],
    ]);
}
```

**Comment by skyzyx** [comment]
That's because `null` is not an Integer. It can be `0`, but not `null`.

In GraphQL, real types (not this _truthy_/_falsey_ stuff) matter a lot.

**Comment by Jalle19** [comment]
Fixed in https://github.com/youshido-php/GraphQL/pull/226
