### ISSUE TITLE
String values with backslash escapes are not being unescaped when processing requests.

### ISSUE THREAD

**Issue by mlitwin** [youshido-php/GraphQL#195]
Bug: String values with backslash escapes are not being unescaped when processing requests.

[Note I'm ready with a PR for a proposed fix, assuming that you agree that escaping the strings is in fact the correct behavior]

Per http://facebook.github.io/graphql/October2016/#sec-String-Value
strings can have escape sequences.

The values parsed and returned in Tokenizer::scanString() are the raw values.
It seems like they should be processed into their unescaped form, otherwise
it's hard to figure out what strings in the system have been feed in in a
escaped form, vs those that have for example been json_decoded from the 'variables'
array. This would be analogous to parseNumber etc, where there is a transformation applied.

To reproduce:

    composer init -n
    composer require youshido/graphql

    php escapedString-index.php

    The input variable is a 2 character string (backslash, quote)
    According to the schema, that resolves to a string of 1 character (quote)

    The output is (after json_decode) a 2 character string (backslash, quote)

[escapedString-index.php.zip](https://github.com/Youshido/GraphQL/files/1583451/escapedString-index.php.zip)

**Comment by mlitwin** [comment]
See PR #196

**Comment by asheliahut** [comment]
👍 This issue I have noticed too. It doesn't seem to be a think with json input but with graphql input

**Comment by asheliahut** [comment]
@viniychuk Is there any way to close this and get it into a tag? Since the PR from @mlitwin was merged fixing the issue.

**Comment by skyzyx** [comment]
PR #196 was merged, so this issue can be closed.

/cc @portey, @viniychuk
