### ISSUE TITLE
thrown an error when type name already exists

### ISSUE THREAD

**Issue by mathroc** [youshido-php/GraphQL#201]
sometime we copy and paste some types classes to bootstrap new types and it happen that we forget to update the type name. it causes problem with the documentation generation. graphiql become unusable for those types.

so it would be nice if the library could warn us when we override an existing type

**Comment by skyzyx** [comment]
How would you propose that this be addressed? As an up-front exception? As a lazy exception? Is this something that could be caught with a functional test or integration test?

**Comment by mathroc** [comment]
I don't know what you mean by a lazy exception. but a regular, up-front exception seems the way to go. unless there's a good reason to register types with same name, but I don't think there is
