### ISSUE TITLE
How to pass ListType as argument ?

### ISSUE THREAD

**Issue by faizanakram99** [youshido-php/GraphQL#213]
Please update documentation with more examples and use cases, I am trying to add ListType as arguments but I don't know how to add it
Something like this

```
 $config->addArguments([
            'entities' => [
                'type' => new ListType(new StringType()),
            ],
            'id' => [
                'type' => new StringType(),
            ],
])

```

which would be equivalent to something like this

```
{
  generic(entities: {name: Relatie}) {
    id
    code
    bedrijfsnaam
    verkortecode
    opmerkingen
  }
}
```

How do I specify 'name' key in building arguments ?

**Comment by Asone** [comment]
@faizanakram99 : 

`ListType` does not support Associative array, only iterable arrays. If you wish to handle associative arrays you'll have to implement your own Type extending `AbstractScalarType`.
