### ISSUE TITLE
[not an issue] GraphQL Psr7 middleware based on your library

### ISSUE THREAD

**Issue by stefanorg** [youshido-php/GraphQL#87]
Hi,
i've created a middleware based on your implementation of GraphQL spec.

https://github.com/stefanorg/graphql-middleware

I've also created a demo app, like you did for symphony, using zend-expressive: https://github.com/stefanorg/graphql-expressive-demo

Feel free to give some feedback!

Thanks for the work done with the library.

**Comment by viniychuk** [comment]
@stefanorg Thanks! Will take a look on later this week

**Comment by portey** [comment]
@stefanorg, it's great!
Especially class `JsonErrorResponseGenerator` is very useful. I'll try this in action and then write a deeper feedback.

Thanks a lot!

**Comment by stefanorg** [comment]
@portey :+1: 
There is no test at the moment, i would like to write some tests but i'm not very good in writing it :(

**Comment by Jalle19** [comment]
Closing this since it's not really an issue
