### ISSUE TITLE
pluggable TypeService

### ISSUE THREAD

**Issue by roippi** [youshido-php/GraphQL#98]
Right now `TypeService` is a collection of static methods.  I'd like to have the ability to modify some of its behaviors:

- We have some particular custom objects that I'd like to return as-is from resolvers to let graphql consume.  Modifying `getPropertyValue` to understand how to consume them doesn't make sense for anyone but me, so I'd like the ability to modify it myself.
- Similar to that, we use a different naming convention for our getters.  Would like the ability to customize that.

Simplest hook I can think of is to implement `Processor#getTypeService` which will return a `TypeService` implementation.

**Comment by viniychuk** [comment]
@roippi While I completely agree with the idea it will be a bit hard to implement it without breaking compatibility. I just tried to fined the best place – it would be resolve method of `ResolvableObjectTrait`. I can inject it into ExecutionContext that is being used there. Will probably push it together with "interfaced" update.

**Comment by roippi** [comment]
That sounds good, I'm not tied to any specific implementation.  Thanks for your work.

**Comment by jbbr** [comment]
This would be really helpful.

I'm trying to use this library together with Eloquent models (Laravel/Lumen...). These models have `__call` implemented by default which causes the current `TypeService::getPropertyValue` implementation to always call `get$Field` which does not work with eloquent models by default.

Manually patching the method to include something like this does work:
```js
public static function getPropertyValue($data, $path)
{
    if (is_object($data)) {
        $getter = $path;

        // disable getter logic if object has __call
        $hasMagicGet = method_exists($data, '__call');
        if ($hasMagicGet) {
            return isset($data->$path) ? $data->$path : null;
        }
```

Do you think that this automatic getter lookup makes any sense for object with `__call` magic method? If not this might be a useful change for other users as well as I believe there are other model/schema libraries out there doing their thing with `_call`.

**Comment by fritz-gerneth** [comment]
Personally, I'm not a big fan of using `__call` to get an object properties. There's `__get` for this specific purpose. `__call` is more generic and I see the risk of magically invoking mutating functions by accident. 

The least BC breaking way I could see though is to modify the `TypeService` a bit to make it a static method proxy to some concrete implementation:

```
class TypeService 
{
    private $typeServiceImplementation;

    public function setImplementation(TypeServiceInterface $impl)
    {
          static::$typeServiceImplementation = $impl;
    }

    public function getImplementation()
    {
        if (null === static::$typeServiceImplementation) {
            static:$$typeServiceImplementation = new DefaultTypeServiceImplementation();
        }
        return static:;$typeServiceImplementation;
    }

    public static function resolveNamedType($object)
	{
		return static::getImplementation()->resolveNamedType($object);
	}
	
	// And all the others ...
}

public function DefaultTypeServiceImplementation
{
	// Note that the implementation itself isn't static anymore
	public function resolveNamedType($object)
	{
        if (is_object($object)) {
            if ($object instanceof AbstractType) {
                return $object->getType();
            }
        } elseif (is_null($object)) {
            return null;
        } elseif (is_scalar($object)) {
            return new StringType();
        }

        throw new \Exception('Invalid type');
	}
	
	// And all the others ...
}

```

That should allow you to provide a custom `TypeService` implementation, while keeping the original behavior by default.
